
package org.irdresearch.tbreach2.shared.model;

// Generated Aug 28, 2011 3:01:59 PM by Hibernate Tools 3.4.0.Beta1

/**
 * Contact generated by hbm2java
 */
public class Contact implements java.io.Serializable
{

	/**
	 * 
	 */
	private static final long	serialVersionUID	= -7006967582096877311L;
	private String				pid;
	private String				addressHouse;
	private String				addressStreet;
	private String				addressSector;
	private String				addressColony;
	private String				addressTown;
	private String				addressUc;
	private String				addressLandMark;
	private String				city;
	private String				country;
	private String				region;
	private String				phone;
	private String				phoneOwner;
	private String				mobile;
	private String				mobileOwner;
	private String				email;
	private String				addressHouse2;
	private String				addressStreet2;
	private String				addressSector2;
	private String				addressColony2;
	private String				addressTown2;
	private String				addressUc2;
	private String				addressLandMark2;
	private String				city2;
	private String				country2;
	private String				region2;
	private String				phone2;
	private String				mobile2;
	private String				email2;
	private Float				locationLat;
	private Float				locationLon;
	private Float				locationLat2;
	private Float				locationLon2;
	private String				meterNo;
	private String				irdstructureNo;

	public Contact ()
	{
	}

	public Contact (String pid)
	{
		this.pid = pid;
	}

	public Contact (String pid, String addressHouse, String addressStreet, String addressSector, String addressColony, String addressTown, String addressUc, String addressLandMark, String city,
			String country, String region, String phone, String phoneOwner, String mobile, String mobileOwner, String email, String addressHouse2, String addressStreet2, String addressSector2,
			String addressColony2, String addressTown2, String addressUc2, String addressLandMark2, String city2, String country2, String region2, String phone2, String mobile2, String email2,
			Float locationLat, Float locationLon, Float locationLat2, Float locationLon2, String meterNo, String irdstructureNo)
	{
		this.pid = pid;
		this.addressHouse = addressHouse;
		this.addressStreet = addressStreet;
		this.addressSector = addressSector;
		this.addressColony = addressColony;
		this.addressTown = addressTown;
		this.addressUc = addressUc;
		this.addressLandMark = addressLandMark;
		this.city = city;
		this.country = country;
		this.region = region;
		this.phone = phone;
		this.phoneOwner = phoneOwner;
		this.mobile = mobile;
		this.mobileOwner = mobileOwner;
		this.email = email;
		this.addressHouse2 = addressHouse2;
		this.addressStreet2 = addressStreet2;
		this.addressSector2 = addressSector2;
		this.addressColony2 = addressColony2;
		this.addressTown2 = addressTown2;
		this.addressUc2 = addressUc2;
		this.addressLandMark2 = addressLandMark2;
		this.city2 = city2;
		this.country2 = country2;
		this.region2 = region2;
		this.phone2 = phone2;
		this.mobile2 = mobile2;
		this.email2 = email2;
		this.locationLat = locationLat;
		this.locationLon = locationLon;
		this.locationLat2 = locationLat2;
		this.locationLon2 = locationLon2;
		this.meterNo = meterNo;
		this.irdstructureNo = irdstructureNo;
	}

	public String getPid ()
	{
		return this.pid;
	}

	public void setPid (String pid)
	{
		this.pid = pid;
	}

	public String getAddressHouse ()
	{
		return this.addressHouse;
	}

	public void setAddressHouse (String addressHouse)
	{
		this.addressHouse = addressHouse;
	}

	public String getAddressStreet ()
	{
		return this.addressStreet;
	}

	public void setAddressStreet (String addressStreet)
	{
		this.addressStreet = addressStreet;
	}

	public String getAddressSector ()
	{
		return this.addressSector;
	}

	public void setAddressSector (String addressSector)
	{
		this.addressSector = addressSector;
	}

	public String getAddressColony ()
	{
		return this.addressColony;
	}

	public void setAddressColony (String addressColony)
	{
		this.addressColony = addressColony;
	}

	public String getAddressTown ()
	{
		return this.addressTown;
	}

	public void setAddressTown (String addressTown)
	{
		this.addressTown = addressTown;
	}

	public String getAddressUc ()
	{
		return this.addressUc;
	}

	public void setAddressUc (String addressUc)
	{
		this.addressUc = addressUc;
	}

	public String getAddressLandMark ()
	{
		return this.addressLandMark;
	}

	public void setAddressLandMark (String addressLandMark)
	{
		this.addressLandMark = addressLandMark;
	}

	public String getCity ()
	{
		return this.city;
	}

	public void setCity (String city)
	{
		this.city = city;
	}

	public String getCountry ()
	{
		return this.country;
	}

	public void setCountry (String country)
	{
		this.country = country;
	}

	public String getRegion ()
	{
		return this.region;
	}

	public void setRegion (String region)
	{
		this.region = region;
	}

	public String getPhone ()
	{
		return this.phone;
	}

	public void setPhone (String phone)
	{
		this.phone = phone;
	}

	public String getPhoneOwner ()
	{
		return this.phoneOwner;
	}

	public void setPhoneOwner (String phoneOwner)
	{
		this.phoneOwner = phoneOwner;
	}

	public String getMobile ()
	{
		return this.mobile;
	}

	public void setMobile (String mobile)
	{
		this.mobile = mobile;
	}

	public String getMobileOwner ()
	{
		return this.mobileOwner;
	}

	public void setMobileOwner (String mobileOwner)
	{
		this.mobileOwner = mobileOwner;
	}

	public String getEmail ()
	{
		return this.email;
	}

	public void setEmail (String email)
	{
		this.email = email;
	}

	public String getAddressHouse2 ()
	{
		return this.addressHouse2;
	}

	public void setAddressHouse2 (String addressHouse2)
	{
		this.addressHouse2 = addressHouse2;
	}

	public String getAddressStreet2 ()
	{
		return this.addressStreet2;
	}

	public void setAddressStreet2 (String addressStreet2)
	{
		this.addressStreet2 = addressStreet2;
	}

	public String getAddressSector2 ()
	{
		return this.addressSector2;
	}

	public void setAddressSector2 (String addressSector2)
	{
		this.addressSector2 = addressSector2;
	}

	public String getAddressColony2 ()
	{
		return this.addressColony2;
	}

	public void setAddressColony2 (String addressColony2)
	{
		this.addressColony2 = addressColony2;
	}

	public String getAddressTown2 ()
	{
		return this.addressTown2;
	}

	public void setAddressTown2 (String addressTown2)
	{
		this.addressTown2 = addressTown2;
	}

	public String getAddressUc2 ()
	{
		return this.addressUc2;
	}

	public void setAddressUc2 (String addressUc2)
	{
		this.addressUc2 = addressUc2;
	}

	public String getAddressLandMark2 ()
	{
		return this.addressLandMark2;
	}

	public void setAddressLandMark2 (String addressLandMark2)
	{
		this.addressLandMark2 = addressLandMark2;
	}

	public String getCity2 ()
	{
		return this.city2;
	}

	public void setCity2 (String city2)
	{
		this.city2 = city2;
	}

	public String getCountry2 ()
	{
		return this.country2;
	}

	public void setCountry2 (String country2)
	{
		this.country2 = country2;
	}

	public String getRegion2 ()
	{
		return this.region2;
	}

	public void setRegion2 (String region2)
	{
		this.region2 = region2;
	}

	public String getPhone2 ()
	{
		return this.phone2;
	}

	public void setPhone2 (String phone2)
	{
		this.phone2 = phone2;
	}

	public String getMobile2 ()
	{
		return this.mobile2;
	}

	public void setMobile2 (String mobile2)
	{
		this.mobile2 = mobile2;
	}

	public String getEmail2 ()
	{
		return this.email2;
	}

	public void setEmail2 (String email2)
	{
		this.email2 = email2;
	}

	public Float getLocationLat ()
	{
		return this.locationLat;
	}

	public void setLocationLat (Float locationLat)
	{
		this.locationLat = locationLat;
	}

	public Float getLocationLon ()
	{
		return this.locationLon;
	}

	public void setLocationLon (Float locationLon)
	{
		this.locationLon = locationLon;
	}

	public Float getLocationLat2 ()
	{
		return this.locationLat2;
	}

	public void setLocationLat2 (Float locationLat2)
	{
		this.locationLat2 = locationLat2;
	}

	public Float getLocationLon2 ()
	{
		return this.locationLon2;
	}

	public void setLocationLon2 (Float locationLon2)
	{
		this.locationLon2 = locationLon2;
	}

	public String getMeterNo ()
	{
		return this.meterNo;
	}

	public void setMeterNo (String meterNo)
	{
		this.meterNo = meterNo;
	}

	public String getIrdstructureNo ()
	{
		return this.irdstructureNo;
	}

	public void setIrdstructureNo (String irdstructureNo)
	{
		this.irdstructureNo = irdstructureNo;
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString ()
	{
		return pid + ", " + addressHouse + ", " + addressStreet + ", " + addressSector + ", " + addressColony + ", " + addressTown + ", " + addressUc + ", " + addressLandMark + ", " + city + ", "
				+ country + ", " + region + ", " + phone + ", " + phoneOwner + ", " + mobile + ", " + mobileOwner + ", " + email + ", " + addressHouse2 + ", " + addressStreet2 + ", " + addressSector2
				+ ", " + addressColony2 + ", " + addressTown2 + ", " + addressUc2 + ", " + addressLandMark2 + ", " + city2 + ", " + country2 + ", " + region2 + ", " + phone2 + ", " + mobile2 + ", "
				+ email2 + ", " + locationLat + ", " + locationLon + ", " + locationLat2 + ", " + locationLon2 + ", " + meterNo + ", " + irdstructureNo;
	}
}
