
package org.irdresearch.tbreach2.shared.model;

// Generated Aug 28, 2011 3:01:59 PM by Hibernate Tools 3.4.0.Beta1

/**
 * DefinitionId generated by hbm2java
 */
public class DefinitionId implements java.io.Serializable
{

	/**
	 * 
	 */
	private static final long	serialVersionUID	= 8045335937502253880L;
	private String				definitionType;
	private String				definitionKey;

	public DefinitionId ()
	{
	}

	public DefinitionId (String definitionType, String key)
	{
		this.definitionType = definitionType;
		this.definitionKey = key;
	}

	public String getDefinitionType ()
	{
		return this.definitionType;
	}

	public void setDefinitionType (String definitionType)
	{
		this.definitionType = definitionType;
	}

	public String getDefinitionKey ()
	{
		return this.definitionKey;
	}

	public void setDefinitionKey (String definitionKey)
	{
		this.definitionKey = definitionKey;
	}

	public boolean equals (Object other)
	{
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DefinitionId))
			return false;
		DefinitionId castOther = (DefinitionId) other;

		return ((this.getDefinitionType () == castOther.getDefinitionType ()) || (this.getDefinitionType () != null && castOther.getDefinitionType () != null && this.getDefinitionType ().equals (
				castOther.getDefinitionType ())))
				&& ((this.getDefinitionKey () == castOther.getDefinitionKey ()) || (this.getDefinitionKey () != null && castOther.getDefinitionKey () != null && this.getDefinitionKey ().equals (
						castOther.getDefinitionKey ())));
	}

	public int hashCode ()
	{
		int result = 17;

		result = 37 * result + (getDefinitionType () == null ? 0 : this.getDefinitionType ().hashCode ());
		result = 37 * result + (getDefinitionKey () == null ? 0 : this.getDefinitionKey ().hashCode ());
		return result;
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString ()
	{
		return definitionType + ", " + definitionKey;
	}

}
