
package org.irdresearch.tbreach2.shared.model;

// Generated Aug 28, 2011 3:01:59 PM by Hibernate Tools 3.4.0.Beta1

/**
 * Definition generated by hbm2java
 */
public class Definition implements java.io.Serializable
{

	/**
	 * 
	 */
	private static final long	serialVersionUID	= 5726563432365973681L;
	private DefinitionId		id;
	private String				value;

	public Definition ()
	{
	}

	public Definition (DefinitionId id, String value)
	{
		this.id = id;
		this.value = value;
	}

	public DefinitionId getId ()
	{
		return this.id;
	}

	public void setId (DefinitionId id)
	{
		this.id = id;
	}

	public String getValue ()
	{
		return this.value;
	}

	public void setValue (String value)
	{
		this.value = value;
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString ()
	{
		return id + ", " + value;
	}

}
