
package org.irdresearch.tbreach2.shared.model;

// Generated Aug 28, 2011 3:57:18 PM by Hibernate Tools 3.4.0.Beta1

/**
 * DrughistoryId generated by hbm2java
 */
public class DrugHistoryId implements java.io.Serializable
{

	/**
	 * 
	 */
	private static final long	serialVersionUID	= -980018934152368513L;
	private String				patientId;
	private int					dispensalNo;

	public DrugHistoryId ()
	{
	}

	public DrugHistoryId (String patientId, int dispensalNo)
	{
		this.patientId = patientId;
		this.dispensalNo = dispensalNo;
	}

	public String getPatientId ()
	{
		return this.patientId;
	}

	public void setPatientId (String patientId)
	{
		this.patientId = patientId;
	}

	public int getDispensalNo ()
	{
		return this.dispensalNo;
	}

	public void setDispensalNo (int dispensalNo)
	{
		this.dispensalNo = dispensalNo;
	}

	public boolean equals (Object other)
	{
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DrugHistoryId))
			return false;
		DrugHistoryId castOther = (DrugHistoryId) other;

		return ((this.getPatientId () == castOther.getPatientId ()) || (this.getPatientId () != null && castOther.getPatientId () != null && this.getPatientId ().equals (castOther.getPatientId ())))
				&& (this.getDispensalNo () == castOther.getDispensalNo ());
	}

	public int hashCode ()
	{
		int result = 17;

		result = 37 * result + (getPatientId () == null ? 0 : this.getPatientId ().hashCode ());
		result = 37 * result + this.getDispensalNo ();
		return result;
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString ()
	{
		return patientId + ", " + dispensalNo;
	}

}
