
package org.irdresearch.tbreach2.shared.model;

// Generated Aug 28, 2011 3:45:30 PM by Hibernate Tools 3.4.0.Beta1

/**
 * EncounterId generated by hbm2java
 */
public class EncounterId implements java.io.Serializable
{

	/**
	 * 
	 */
	private static final long	serialVersionUID	= 5635132381224016660L;
	private int					encounterId;
	private String				pid1;
	private String				pid2;

	public EncounterId ()
	{
	}

	public EncounterId (int encounterId, String pid1, String pid2)
	{
		this.encounterId = encounterId;
		this.pid1 = pid1;
		this.pid2 = pid2;
	}

	public int getEncounterId ()
	{
		return this.encounterId;
	}

	public void setEncounterId (int encounterId)
	{
		this.encounterId = encounterId;
	}

	public String getPid1 ()
	{
		return this.pid1;
	}

	public void setPid1 (String pid1)
	{
		this.pid1 = pid1;
	}

	public String getPid2 ()
	{
		return this.pid2;
	}

	public void setPid2 (String pid2)
	{
		this.pid2 = pid2;
	}

	public boolean equals (Object other)
	{
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof EncounterId))
			return false;
		EncounterId castOther = (EncounterId) other;

		return (this.getEncounterId () == castOther.getEncounterId ())
				&& ((this.getPid1 () == castOther.getPid1 ()) || (this.getPid1 () != null && castOther.getPid1 () != null && this.getPid1 ().equals (castOther.getPid1 ())))
				&& ((this.getPid2 () == castOther.getPid2 ()) || (this.getPid2 () != null && castOther.getPid2 () != null && this.getPid2 ().equals (castOther.getPid2 ())));
	}

	public int hashCode ()
	{
		int result = 17;

		result = 37 * result + this.getEncounterId ();
		result = 37 * result + (getPid1 () == null ? 0 : this.getPid1 ().hashCode ());
		result = 37 * result + (getPid2 () == null ? 0 : this.getPid2 ().hashCode ());
		return result;
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString ()
	{
		return encounterId + ", " + pid1 + ", " + pid2;
	}

}
