
package org.irdresearch.tbreach2.shared.model;

// default package
// Generated Dec 21, 2010 3:45:59 PM by Hibernate Tools 3.4.0.Beta1

/**
 * EncounterResults generated by hbm2java
 */
public class EncounterResults implements java.io.Serializable
{

	/**
	 * 
	 */
	private static final long	serialVersionUID	= -4579364661550124764L;
	private EncounterResultsId	id;
	private String				value;

	public EncounterResults ()
	{
		// Not implemented
	}

	public EncounterResults (EncounterResultsId id, String value)
	{
		this.id = id;
		this.value = value;
	}

	public EncounterResultsId getId ()
	{
		return this.id;
	}

	public void setId (EncounterResultsId id)
	{
		this.id = id;
	}

	public String getValue ()
	{
		return this.value;
	}

	public void setValue (String value)
	{
		this.value = value;
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString ()
	{
		return this.id + ", " + this.value;
	}

}
