
package org.irdresearch.tbreach2.shared.model;

// Generated Aug 28, 2011 3:01:59 PM by Hibernate Tools 3.4.0.Beta1

/**
 * Labmapping generated by hbm2java
 */
public class LabMapping implements java.io.Serializable
{

	/**
	 * 
	 */
	private static final long	serialVersionUID	= -4033824560272125643L;
	private LabMappingId		id;
	private String				pidrole;

	public LabMapping ()
	{
	}

	public LabMapping (LabMappingId id, String pidrole)
	{
		this.id = id;
		this.pidrole = pidrole;
	}

	public LabMappingId getId ()
	{
		return this.id;
	}

	public void setId (LabMappingId id)
	{
		this.id = id;
	}

	public String getPidrole ()
	{
		return this.pidrole;
	}

	public void setPidrole (String pidrole)
	{
		this.pidrole = pidrole;
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString ()
	{
		return id + ", " + pidrole;
	}

}
