
package org.irdresearch.tbreach2.shared.model;

// Generated Aug 28, 2011 3:01:59 PM by Hibernate Tools 3.4.0.Beta1

/**
 * LabmappingId generated by hbm2java
 */
public class LabMappingId implements java.io.Serializable
{

	/**
	 * 
	 */
	private static final long	serialVersionUID	= 4080537435045714571L;
	private String				locationId;
	private String				pid;

	public LabMappingId ()
	{
	}

	public LabMappingId (String locationId, String pid)
	{
		this.locationId = locationId;
		this.pid = pid;
	}

	public String getLocationId ()
	{
		return this.locationId;
	}

	public void setLocationId (String locationId)
	{
		this.locationId = locationId;
	}

	public String getPid ()
	{
		return this.pid;
	}

	public void setPid (String pid)
	{
		this.pid = pid;
	}

	public boolean equals (Object other)
	{
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof LabMappingId))
			return false;
		LabMappingId castOther = (LabMappingId) other;

		return ((this.getLocationId () == castOther.getLocationId ()) || (this.getLocationId () != null && castOther.getLocationId () != null && this.getLocationId ().equals (
				castOther.getLocationId ())))
				&& ((this.getPid () == castOther.getPid ()) || (this.getPid () != null && castOther.getPid () != null && this.getPid ().equals (castOther.getPid ())));
	}

	public int hashCode ()
	{
		int result = 17;

		result = 37 * result + (getLocationId () == null ? 0 : this.getLocationId ().hashCode ());
		result = 37 * result + (getPid () == null ? 0 : this.getPid ().hashCode ());
		return result;
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString ()
	{
		return locationId + ", " + pid;
	}

}
