
package org.irdresearch.tbreach2.shared.model;

// Generated Aug 28, 2011 3:01:59 PM by Hibernate Tools 3.4.0.Beta1

import java.util.Date;

/**
 * LogUserlogin generated by hbm2java
 */
public class Log_UserLogin implements java.io.Serializable
{

	/**
	 * 
	 */
	private static final long	serialVersionUID	= -121357360561827155L;
	private Long				loginNo;
	private String				userId;
	private Date				loginTime;
	private Date				logoutTime;
	private String				remarks;

	public Log_UserLogin ()
	{
	}

	public Log_UserLogin (String userId)
	{
		this.userId = userId;
	}

	public Log_UserLogin (String userId, Date loginTime, Date logoutTime, String remarks)
	{
		this.userId = userId;
		this.loginTime = loginTime;
		this.logoutTime = logoutTime;
		this.remarks = remarks;
	}

	public Long getLoginNo ()
	{
		return this.loginNo;
	}

	public void setLoginNo (Long loginNo)
	{
		this.loginNo = loginNo;
	}

	public String getUserId ()
	{
		return this.userId;
	}

	public void setUserId (String userId)
	{
		this.userId = userId;
	}

	public Date getLoginTime ()
	{
		return this.loginTime;
	}

	public void setLoginTime (Date loginTime)
	{
		this.loginTime = loginTime;
	}

	public Date getLogoutTime ()
	{
		return this.logoutTime;
	}

	public void setLogoutTime (Date logoutTime)
	{
		this.logoutTime = logoutTime;
	}

	public String getRemarks ()
	{
		return this.remarks;
	}

	public void setRemarks (String remarks)
	{
		this.remarks = remarks;
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString ()
	{
		return loginNo + ", " + userId + ", " + loginTime + ", " + logoutTime + ", " + remarks;
	}

}
