
package org.irdresearch.tbreach2.shared.model;

// Generated Aug 28, 2011 3:01:59 PM by Hibernate Tools 3.4.0.Beta1

import java.util.Date;

/**
 * Patient generated by hbm2java
 */
public class Patient implements java.io.Serializable
{

	/**
	 * 
	 */
	private static final long	serialVersionUID	= 4363662398057127527L;
	private String				patientId;
	private String				chwid;
	private String				tswid;
	private String				gpid;
	private String				laboratoryId;
	private String				mrno;
	private String				externalMrno;
	private Float				weight;
	private Float				height;
	private String				bloodGroup;
	private Date				dateRegistered;
	private String				treatmentCenter;
	private Boolean				diseaseSuspected;
	private Boolean				diseaseConfirmed;
	private String				diseaseCategory;
	private String				diseaseSite;
	private String				severity;
	private String				regimen;
	private Float				doseCombination;
	private Integer				streptomycin;
	private String				treatmentSupporter;
	private String				treatmentSupporterContact;
	private String				treatmentSupporterRelationship;
	private String				treatmentPhase;
	private String				patientStatus;
	private String				patientType;
	private String				diseaseHistory;
	private Boolean				treatedPreviously;
	private Integer				previousTreatmentDuration;
	private Boolean				completedPreviousTreatment;
	private String				fullDescription;

	public Patient ()
	{
	}

	public Patient (String patientId)
	{
		this.patientId = patientId;
	}

	public Patient (String patientId, String chwid, String tswid, String gpid, String laboratoryId, String mrno, String externalMrno, Float weight, Float height, String bloodGroup,
			Date dateRegistered, String treatmentCenter, Boolean diseaseSuspected, Boolean diseaseConfirmed, String diseaseCategory, String diseaseSite, String severity, String regimen,
			Float doseCombination, Integer streptomycin, String treatmentSupporter, String treatmentSupporterContact, String treatmentSupporterRelationship, String treatmentPhase,
			String patientStatus, String patientType, String diseaseHistory, Boolean treatedPreviously, Integer previousTreatmentDuration, Boolean completedPreviousTreatment, String fullDescription)
	{
		this.patientId = patientId;
		this.chwid = chwid;
		this.tswid = tswid;
		this.gpid = gpid;
		this.laboratoryId = laboratoryId;
		this.mrno = mrno;
		this.externalMrno = externalMrno;
		this.weight = weight;
		this.height = height;
		this.bloodGroup = bloodGroup;
		this.dateRegistered = dateRegistered;
		this.treatmentCenter = treatmentCenter;
		this.diseaseSuspected = diseaseSuspected;
		this.diseaseConfirmed = diseaseConfirmed;
		this.diseaseCategory = diseaseCategory;
		this.diseaseSite = diseaseSite;
		this.severity = severity;
		this.regimen = regimen;
		this.doseCombination = doseCombination;
		this.streptomycin = streptomycin;
		this.treatmentSupporter = treatmentSupporter;
		this.treatmentSupporterContact = treatmentSupporterContact;
		this.treatmentSupporterRelationship = treatmentSupporterRelationship;
		this.treatmentPhase = treatmentPhase;
		this.patientStatus = patientStatus;
		this.patientType = patientType;
		this.diseaseHistory = diseaseHistory;
		this.treatedPreviously = treatedPreviously;
		this.previousTreatmentDuration = previousTreatmentDuration;
		this.completedPreviousTreatment = completedPreviousTreatment;
		this.fullDescription = fullDescription;
	}

	public String getPatientId ()
	{
		return this.patientId;
	}

	public void setPatientId (String patientId)
	{
		this.patientId = patientId;
	}

	public String getChwid ()
	{
		return this.chwid;
	}

	public void setChwid (String chwid)
	{
		this.chwid = chwid;
	}

	public String getTswid ()
	{
		return this.tswid;
	}

	public void setTswid (String tswid)
	{
		this.tswid = tswid;
	}

	public String getGpid ()
	{
		return this.gpid;
	}

	public void setGpid (String gpid)
	{
		this.gpid = gpid;
	}

	public String getLaboratoryId ()
	{
		return this.laboratoryId;
	}

	public void setLaboratoryId (String laboratoryId)
	{
		this.laboratoryId = laboratoryId;
	}

	public String getMrno ()
	{
		return this.mrno;
	}

	public void setMrno (String mrno)
	{
		this.mrno = mrno;
	}

	public String getExternalMrno ()
	{
		return this.externalMrno;
	}

	public void setExternalMrno (String externalMrno)
	{
		this.externalMrno = externalMrno;
	}

	public Float getWeight ()
	{
		return this.weight;
	}

	public void setWeight (Float weight)
	{
		this.weight = weight;
	}

	public Float getHeight ()
	{
		return this.height;
	}

	public void setHeight (Float height)
	{
		this.height = height;
	}

	public String getBloodGroup ()
	{
		return this.bloodGroup;
	}

	public void setBloodGroup (String bloodGroup)
	{
		this.bloodGroup = bloodGroup;
	}

	public Date getDateRegistered ()
	{
		return this.dateRegistered;
	}

	public void setDateRegistered (Date dateRegistered)
	{
		this.dateRegistered = dateRegistered;
	}

	public String getTreatmentCenter ()
	{
		return this.treatmentCenter;
	}

	public void setTreatmentCenter (String treatmentCenter)
	{
		this.treatmentCenter = treatmentCenter;
	}

	public Boolean getDiseaseSuspected ()
	{
		return this.diseaseSuspected;
	}

	public void setDiseaseSuspected (Boolean diseaseSuspected)
	{
		this.diseaseSuspected = diseaseSuspected;
	}

	public Boolean getDiseaseConfirmed ()
	{
		return this.diseaseConfirmed;
	}

	public void setDiseaseConfirmed (Boolean diseaseConfirmed)
	{
		this.diseaseConfirmed = diseaseConfirmed;
	}

	public String getDiseaseCategory ()
	{
		return this.diseaseCategory;
	}

	public void setDiseaseCategory (String diseaseCategory)
	{
		this.diseaseCategory = diseaseCategory;
	}

	public String getDiseaseSite ()
	{
		return this.diseaseSite;
	}

	public void setDiseaseSite (String diseaseSite)
	{
		this.diseaseSite = diseaseSite;
	}

	public String getSeverity ()
	{
		return this.severity;
	}

	public void setSeverity (String severity)
	{
		this.severity = severity;
	}

	public String getRegimen ()
	{
		return this.regimen;
	}

	public void setRegimen (String regimen)
	{
		this.regimen = regimen;
	}

	public Float getDoseCombination ()
	{
		return this.doseCombination;
	}

	public void setDoseCombination (Float doseCombination)
	{
		this.doseCombination = doseCombination;
	}

	public Integer getStreptomycin ()
	{
		return this.streptomycin;
	}

	public void setStreptomycin (Integer streptomycin)
	{
		this.streptomycin = streptomycin;
	}

	public String getTreatmentSupporter ()
	{
		return this.treatmentSupporter;
	}

	public void setTreatmentSupporter (String treatmentSupporter)
	{
		this.treatmentSupporter = treatmentSupporter;
	}

	public String getTreatmentSupporterContact ()
	{
		return this.treatmentSupporterContact;
	}

	public void setTreatmentSupporterContact (String treatmentSupporterContact)
	{
		this.treatmentSupporterContact = treatmentSupporterContact;
	}

	public String getTreatmentSupporterRelationship ()
	{
		return this.treatmentSupporterRelationship;
	}

	public void setTreatmentSupporterRelationship (String treatmentSupporterRelationship)
	{
		this.treatmentSupporterRelationship = treatmentSupporterRelationship;
	}

	public String getTreatmentPhase ()
	{
		return this.treatmentPhase;
	}

	public void setTreatmentPhase (String treatmentPhase)
	{
		this.treatmentPhase = treatmentPhase;
	}

	public String getPatientStatus ()
	{
		return this.patientStatus;
	}

	public void setPatientStatus (String patientStatus)
	{
		this.patientStatus = patientStatus;
	}

	public String getPatientType ()
	{
		return this.patientType;
	}

	public void setPatientType (String patientType)
	{
		this.patientType = patientType;
	}

	public String getDiseaseHistory ()
	{
		return this.diseaseHistory;
	}

	public void setDiseaseHistory (String diseaseHistory)
	{
		this.diseaseHistory = diseaseHistory;
	}

	public Boolean getTreatedPreviously ()
	{
		return this.treatedPreviously;
	}

	public void setTreatedPreviously (Boolean treatedPreviously)
	{
		this.treatedPreviously = treatedPreviously;
	}

	public Integer getPreviousTreatmentDuration ()
	{
		return this.previousTreatmentDuration;
	}

	public void setPreviousTreatmentDuration (Integer previousTreatmentDuration)
	{
		this.previousTreatmentDuration = previousTreatmentDuration;
	}

	public Boolean getCompletedPreviousTreatment ()
	{
		return this.completedPreviousTreatment;
	}

	public void setCompletedPreviousTreatment (Boolean completedPreviousTreatment)
	{
		this.completedPreviousTreatment = completedPreviousTreatment;
	}

	public String getFullDescription ()
	{
		return this.fullDescription;
	}

	public void setFullDescription (String fullDescription)
	{
		this.fullDescription = fullDescription;
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString ()
	{
		return patientId + ", " + chwid + ", " + tswid + ", " + gpid + ", " + laboratoryId + ", " + mrno + ", " + externalMrno + ", " + weight + ", " + height + ", " + bloodGroup + ", "
				+ dateRegistered + ", " + treatmentCenter + ", " + diseaseSuspected + ", " + diseaseConfirmed + ", " + diseaseCategory + ", " + diseaseSite + ", " + severity + ", " + regimen + ", "
				+ doseCombination + ", " + streptomycin + ", " + treatmentSupporter + ", " + treatmentSupporterContact + ", " + treatmentSupporterRelationship + ", " + treatmentPhase + ", "
				+ patientStatus + ", " + patientType + ", " + diseaseHistory + ", " + treatedPreviously + ", " + previousTreatmentDuration + ", " + completedPreviousTreatment + ", " + fullDescription;
	}

}
