
package org.irdresearch.tbreach2.shared.model;

// Generated Aug 28, 2011 3:58:51 PM by Hibernate Tools 3.4.0.Beta1

import java.util.Date;

/**
 * Sputumresults generated by hbm2java
 */
public class SputumResults implements java.io.Serializable
{

	/**
	 * 
	 */
	private static final long	serialVersionUID	= 6808833601626096886L;
	private int					sputumOrderNo;
	private String				patientId;
/*	private int					sputumId;
	private String				sputumLabId;
	private int					month;
	private String				smearOrderedBy;
	private Date				smearOrderDate;
	private Boolean				instructionsGiven;
	private String				sputumProduced;
	private String				sputumQuality;
	private Boolean				smearTestDone;
*/	private Date				dateSmearTested;
	private String				smearResult;
	private String				smearResult2;
	private String				smearResult3;
	private int 				labNumber;
	private String 				treatmentFacility;
/*	private String				smearEnteredBy;
	private String				geneXpertOrderedBy;
	private Date				geneXpertOrderDate;
	private Boolean				geneXpertTestDone;
	private Date				dateGeneXpertTested;
	private String				geneXpertResult;
	private String				geneXpertResistance;
	private String				geneXpertEnteredBy;
	private String				details;
*/
	public SputumResults ()
	{
	}

	public SputumResults (int sputumOrderNo, String patientId, int sputumId, int month)
	{
		this.sputumOrderNo = sputumOrderNo;
		this.patientId = patientId;
/*		this.sputumId = sputumId;
		this.month = month;
*/	}

	public SputumResults (int sputumOrderNo, String patientId, Date dateSmearTested, String smearResult, String smearResult2, String smearResult3, int labNumber
			,String treatmentFacility)
	{
		this.sputumOrderNo = sputumOrderNo;
		this.patientId = patientId;
		this.labNumber = labNumber;
		this.treatmentFacility = treatmentFacility;
/*		this.sputumId = sputumId;
		this.sputumLabId = sputumLabId;
		this.month = month;
		this.smearOrderedBy = smearOrderedBy;
		this.smearOrderDate = smearOrderDate;
		this.instructionsGiven = instructionsGiven;
		this.sputumProduced = sputumProduced;
		this.sputumQuality = sputumQuality;
		this.smearTestDone = smearTestDone;
*/		this.dateSmearTested = dateSmearTested;
		this.smearResult = smearResult;
/*		this.smearEnteredBy = smearEnteredBy;
		this.geneXpertOrderedBy = geneXpertOrderedBy;
		this.geneXpertOrderDate = geneXpertOrderDate;
		this.geneXpertTestDone = geneXpertTestDone;
		this.dateGeneXpertTested = dateGeneXpertTested;
		this.geneXpertResult = geneXpertResult;
		this.geneXpertResistance = geneXpertResistance;
		this.geneXpertEnteredBy = geneXpertEnteredBy;
		this.details = details;
*/	}

	public int getLabNumber() {
		return labNumber;
	}

	public void setLabNumber(int labNumber) {
		this.labNumber = labNumber;
	}

	public String getTreatmentFacility() {
		return treatmentFacility;
	}

	public void setTreatmentFacility(String treatmentFacility) {
		this.treatmentFacility = treatmentFacility;
	}

	public String getSmearResult2() {
		return smearResult2;
	}

	public void setSmearResult2(String smearResult2) {
		this.smearResult2 = smearResult2;
	}

	public String getSmearResult3() {
		return smearResult3;
	}

	public void setSmearResult3(String smearResult3) {
		this.smearResult3 = smearResult3;
	}

	public int getSputumOrderNo ()
	{
		return this.sputumOrderNo;
	}

	public void setSputumOrderNo (int sputumOrderNo)
	{
		this.sputumOrderNo = sputumOrderNo;
	}

	public String getPatientId ()
	{
		return this.patientId;
	}

	public void setPatientId (String patientId)
	{
		this.patientId = patientId;
	}

/*	public int getSputumId ()
	{
		return this.sputumId;
	}

	public void setSputumId (int sputumId)
	{
		this.sputumId = sputumId;
	}

	public String getSputumLabId ()
	{
		return this.sputumLabId;
	}

	public void setSputumLabId (String sputumLabId)
	{
		this.sputumLabId = sputumLabId;
	}

	public int getMonth ()
	{
		return this.month;
	}

	public void setMonth (int month)
	{
		this.month = month;
	}

	public String getSmearOrderedBy ()
	{
		return this.smearOrderedBy;
	}

	public void setSmearOrderedBy (String smearOrderedBy)
	{
		this.smearOrderedBy = smearOrderedBy;
	}

	public Date getSmearOrderDate ()
	{
		return this.smearOrderDate;
	}

	public void setSmearOrderDate (Date smearOrderDate)
	{
		this.smearOrderDate = smearOrderDate;
	}

	public Boolean getInstructionsGiven ()
	{
		return this.instructionsGiven;
	}

	public void setInstructionsGiven (Boolean instructionsGiven)
	{
		this.instructionsGiven = instructionsGiven;
	}

	public String getSputumProduced ()
	{
		return this.sputumProduced;
	}

	public void setSputumProduced (String sputumProduced)
	{
		this.sputumProduced = sputumProduced;
	}

	public String getSputumQuality ()
	{
		return this.sputumQuality;
	}

	public void setSputumQuality (String sputumQuality)
	{
		this.sputumQuality = sputumQuality;
	}

	public Boolean getSmearTestDone ()
	{
		return this.smearTestDone;
	}

	public void setSmearTestDone (Boolean smearTestDone)
	{
		this.smearTestDone = smearTestDone;
	}
*/
	public Date getDateSmearTested ()
	{
		return this.dateSmearTested;
	}

	public void setDateSmearTested (Date dateSmearTested)
	{
		this.dateSmearTested = dateSmearTested;
	}

	public String getSmearResult ()
	{
		return this.smearResult;
	}

	public void setSmearResult (String smearResult)
	{
		this.smearResult = smearResult;
	}

/*	public String getSmearEnteredBy ()
	{
		return this.smearEnteredBy;
	}

	public void setSmearEnteredBy (String smearEnteredBy)
	{
		this.smearEnteredBy = smearEnteredBy;
	}

	public String getGeneXpertOrderedBy ()
	{
		return this.geneXpertOrderedBy;
	}

	public void setGeneXpertOrderedBy (String geneXpertOrderedBy)
	{
		this.geneXpertOrderedBy = geneXpertOrderedBy;
	}

	public Date getGeneXpertOrderDate ()
	{
		return this.geneXpertOrderDate;
	}

	public void setGeneXpertOrderDate (Date geneXpertOrderDate)
	{
		this.geneXpertOrderDate = geneXpertOrderDate;
	}

	public Boolean getGeneXpertTestDone ()
	{
		return this.geneXpertTestDone;
	}

	public void setGeneXpertTestDone (Boolean geneXpertTestDone)
	{
		this.geneXpertTestDone = geneXpertTestDone;
	}

	public Date getDateGeneXpertTested ()
	{
		return this.dateGeneXpertTested;
	}

	public void setDateGeneXpertTested (Date dateGeneXpertTested)
	{
		this.dateGeneXpertTested = dateGeneXpertTested;
	}

	public String getGeneXpertResult ()
	{
		return this.geneXpertResult;
	}

	public void setGeneXpertResult (String geneXpertResult)
	{
		this.geneXpertResult = geneXpertResult;
	}

	public String getGeneXpertResistance ()
	{
		return this.geneXpertResistance;
	}

	public void setGeneXpertResistance (String geneXpertResistance)
	{
		this.geneXpertResistance = geneXpertResistance;
	}

	public String getGeneXpertEnteredBy ()
	{
		return this.geneXpertEnteredBy;
	}

	public void setGeneXpertEnteredBy (String geneXpertEnteredBy)
	{
		this.geneXpertEnteredBy = geneXpertEnteredBy;
	}

	public String getDetails ()
	{
		return this.details;
	}

	public void setDetails (String details)
	{
		this.details = details;
	}
*/
	/*
	 * (non-Javadoc)
	 * 
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString ()
	{
		return sputumOrderNo + ", " + patientId + ", " + /*sputumId + ", " + sputumLabId + ", " + month + ", " + smearOrderedBy + ", " + smearOrderDate + ", " + instructionsGiven + ", "
				+ sputumProduced + ", " + sputumQuality + ", " + smearTestDone + ", " +*/ dateSmearTested + ", " + smearResult+", " + smearResult2+", "+smearResult3; /*+ ", " + smearEnteredBy + ", " + geneXpertOrderedBy + ", "
				+ geneXpertOrderDate + ", " + geneXpertTestDone + ", " + dateGeneXpertTested + ", " + geneXpertResult + ", " + geneXpertResistance + ", " + geneXpertEnteredBy + ", " + details;
	*/}

}
