
package org.irdresearch.tbreach2.shared.model;

// Generated Aug 28, 2011 3:01:59 PM by Hibernate Tools 3.4.0.Beta1

/**
 * UserRightsId generated by hbm2java
 */
public class UserRightsId implements java.io.Serializable
{

	/**
	 * 
	 */
	private static final long	serialVersionUID	= 2456517329009945192L;
	private String				role;
	private String				menuName;

	public UserRightsId ()
	{
	}

	public UserRightsId (String role, String menuName)
	{
		this.role = role;
		this.menuName = menuName;
	}

	public String getRole ()
	{
		return this.role;
	}

	public void setRole (String role)
	{
		this.role = role;
	}

	public String getMenuName ()
	{
		return this.menuName;
	}

	public void setMenuName (String menuName)
	{
		this.menuName = menuName;
	}

	public boolean equals (Object other)
	{
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UserRightsId))
			return false;
		UserRightsId castOther = (UserRightsId) other;

		return ((this.getRole () == castOther.getRole ()) || (this.getRole () != null && castOther.getRole () != null && this.getRole ().equals (castOther.getRole ())))
				&& ((this.getMenuName () == castOther.getMenuName ()) || (this.getMenuName () != null && castOther.getMenuName () != null && this.getMenuName ().equals (castOther.getMenuName ())));
	}

	public int hashCode ()
	{
		int result = 17;

		result = 37 * result + (getRole () == null ? 0 : this.getRole ().hashCode ());
		result = 37 * result + (getMenuName () == null ? 0 : this.getMenuName ().hashCode ());
		return result;
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString ()
	{
		return role + ", " + menuName;
	}

}
