
package org.irdresearch.tbreach2.shared.model;

// Generated Aug 28, 2011 3:01:59 PM by Hibernate Tools 3.4.0.Beta1

import java.util.Date;

/**
 * XrayResults generated by hbm2java
 */
public class XrayResults implements java.io.Serializable
{

	/**
	 * 
	 */
	private static final long	serialVersionUID	= 4718984808915692765L;
	private String				patientId;
	private String				xrayOrderedBy;
	private String				xrayLabId;
	private Date				xrayDate;
	private Date				dateReported;
	private String				xrayResult;
	private String				testedBy;
	private String				remarks;

	public XrayResults ()
	{
	}

	public XrayResults (String patientId)
	{
		this.patientId = patientId;
	}

	public XrayResults (String patientId, String xrayOrderedBy, String xrayLabId, Date xrayDate, Date dateReported, String xrayResult, String testedBy, String remarks)
	{
		this.patientId = patientId;
		this.xrayOrderedBy = xrayOrderedBy;
		this.xrayLabId = xrayLabId;
		this.xrayDate = xrayDate;
		this.dateReported = dateReported;
		this.xrayResult = xrayResult;
		this.testedBy = testedBy;
		this.remarks = remarks;
	}

	public String getPatientId ()
	{
		return this.patientId;
	}

	public void setPatientId (String patientId)
	{
		this.patientId = patientId;
	}

	public String getXrayOrderedBy ()
	{
		return this.xrayOrderedBy;
	}

	public void setXrayOrderedBy (String xrayOrderedBy)
	{
		this.xrayOrderedBy = xrayOrderedBy;
	}

	public String getXrayLabId ()
	{
		return this.xrayLabId;
	}

	public void setXrayLabId (String xrayLabId)
	{
		this.xrayLabId = xrayLabId;
	}

	public Date getXrayDate ()
	{
		return this.xrayDate;
	}

	public void setXrayDate (Date xrayDate)
	{
		this.xrayDate = xrayDate;
	}

	public Date getDateReported ()
	{
		return this.dateReported;
	}

	public void setDateReported (Date dateReported)
	{
		this.dateReported = dateReported;
	}

	public String getXrayResult ()
	{
		return this.xrayResult;
	}

	public void setXrayResult (String xrayResult)
	{
		this.xrayResult = xrayResult;
	}

	public String getTestedBy ()
	{
		return this.testedBy;
	}

	public void setTestedBy (String testedBy)
	{
		this.testedBy = testedBy;
	}

	public String getRemarks ()
	{
		return this.remarks;
	}

	public void setRemarks (String remarks)
	{
		this.remarks = remarks;
	}

}
